export {
  adminReportsApi,
  adminReportsService,
} from "./api/admin-reports.api";

export type {
  AdminReportQuery,
  AdminReportFilters,
  AdminKpisResponse,
  AdminSummaryResponse,
  AdminActivityBreakdownResponse,
  AdminActivityBreakdownSales,
  AdminActivityBreakdownReservations,
  AdminActivityBreakdownOperations,
  AdminRevenueResponse,
  AdminSalesTrendPoint,
  AdminSalesTrendResponse,
  AdminProfitLossResponse,
  AdminPaymentMethodItem,
  AdminPaymentMethodsResponse,
  AdminPaymentsResponse,
  AdminInventoryBucket,
  AdminInventoryResponse,
  AdminProductPerformanceRow,
  AdminProductsResponse,
  AdminBranchPerformanceRow,
  AdminBranchesResponse,
  AdminReturnsExchangesResponse,
  AdminExpenseByBranch,
  AdminExpenseByType,
  AdminExpensesResponse,
  AdminGeneralSummary,
  AdminGeneralTopProduct,
  AdminGeneralRecentOperation,
  AdminGeneralPaymentMethod,
  AdminGeneralSalesTrendPoint,
  AdminGeneralSalesTrend,
} from "./types/admin-reports.types";

export {
  buildAdminReportQuery,
  buildGeneralSalesTrendQuery,
  normalizeGeneralSummary,
  extractPaymentMethodItems,
  extractSalesTrendPoints,
  extractAdminProducts,
  extractAdminBranches,
  extractGeneralTopProducts,
  extractGeneralRecentOperations,
} from "./helpers/admin-reports.helper";
