export type {
  NamedRef,
  AcademicYearRef,
  ProductType,
  ProductStatus,
  ProductAvailabilityStatus,
  ProductResponse,
  ProductSearchBranch,
  ProductSearchResponse,
  ProductQuery,
  ProductSearchQuery,
  ProductPayload,
  ProductUpdatePayload,
  ProductStatusPayload,
  ProductListItem,
} from "./product.types";
